# Generated by Django 2.1.5 on 2019-03-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_exams_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exams',
            new_name='Exam',
        ),
    ]
