# Generated by Django 2.1.5 on 2019-03-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190312_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
