# Generated by Django 2.1.5 on 2019-03-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_exam_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_id',
            new_name='klasse',
        ),
    ]
